export const supportedSets = [
  'Capenna',
  'Kamigawa',
  'Innistrad',
  'Forgotten Realms',
  'Strixhaven',
  'Throne of Eldraine',
  'Theros Beyond Death',
  'Ikoria: Lair of Behemoths',
  'Core Set 2021',
  'Zendikar Rising',
  'Kaldheim',
  'Core Set 2020',
  'War of the Spark',
  'Ravnica Allegiance',
  'Guilds of Ravnica',
  'Ixalan',
  'Rivals of Ixalan',
  'Dominaria',
  'Core Set 2019',
  'Historic Anthology',
  'Historic Anthology 2',
  'Historic Anthology 3',
  'Jumpstart',
  'Amonkhet Remastered',
  'Kaladesh Remastered'
]